blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Server
    url: https://discord.gg/bHjKNkN
    about: Please ask and answer questions here.
  - name: Homebridge-Wemo - Pull Requests
    url: https://github.com/donavanbecker/homebridge-wemo/pulls
    about: Please report security vulnerabilities here.
